/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feladat_0408;

/**
 *
 * @author Kenaros
 */
public class Ablak extends javax.swing.JFrame {

    private int helyesEredmeny, probadb;

    /**
     * Creates new form Ablak
     */
    public Ablak() {
        initComponents();
        probadb = 0;
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HelyesseBT = new javax.swing.ButtonGroup();
        pnTerulet = new javax.swing.JPanel();
        lbFeladat = new javax.swing.JLabel();
        txtTip = new javax.swing.JTextField();
        lbProbalkozas = new javax.swing.JLabel();
        dbKerdes = new javax.swing.JLabel();
        btSzamol = new javax.swing.JButton();
        btUjFeladat = new javax.swing.JButton();
        rbHejes = new javax.swing.JRadioButton();
        rbRossz = new javax.swing.JRadioButton();
        lbUzenet = new javax.swing.JLabel();
        pnStat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        statTextArea = new javax.swing.JTextArea();
        meBar = new javax.swing.JMenuBar();
        meMuvelet = new javax.swing.JMenu();
        meOsszeadas = new javax.swing.JMenuItem();
        meKivonas = new javax.swing.JMenuItem();
        meSzorzas = new javax.swing.JMenuItem();
        meOsztas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alap Müvelet gyakorlas");

        pnTerulet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbFeladat.setText("A feladat");

        lbProbalkozas.setText("Eddig próbálkozott: 0");

        dbKerdes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dbKerdes.setText("Kérdések száma: 0");

        btSzamol.setText("Számol");
        btSzamol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSzamolActionPerformed(evt);
            }
        });

        btUjFeladat.setText("Új Feladat");
        btUjFeladat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUjFeladatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTeruletLayout = new javax.swing.GroupLayout(pnTerulet);
        pnTerulet.setLayout(pnTeruletLayout);
        pnTeruletLayout.setHorizontalGroup(
            pnTeruletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTeruletLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbProbalkozas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addGroup(pnTeruletLayout.createSequentialGroup()
                .addGroup(pnTeruletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTeruletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnTeruletLayout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addComponent(btSzamol, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btUjFeladat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnTeruletLayout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(lbFeladat, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)
                            .addComponent(txtTip, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnTeruletLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(dbKerdes, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnTeruletLayout.setVerticalGroup(
            pnTeruletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTeruletLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dbKerdes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTeruletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFeladat, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnTeruletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSzamol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btUjFeladat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lbProbalkozas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        HelyesseBT.add(rbHejes);
        rbHejes.setText("Helyes megoldás");
        rbHejes.setEnabled(false);

        HelyesseBT.add(rbRossz);
        rbRossz.setText("Rossz megoldás");
        rbRossz.setEnabled(false);

        lbUzenet.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lbUzenet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        pnStat.setBorder(javax.swing.BorderFactory.createTitledBorder("Statisztika"));
        pnStat.setToolTipText("Statisztika: Összeadás: 0 Kivonás: 0 Szorzás: 0 Osztás: 0  Átlagosan: 100%");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        statTextArea.setColumns(20);
        statTextArea.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        statTextArea.setRows(5);
        statTextArea.setText("Statisztika:\nÖsszeadás: 0\nKivonás: 0\nSzorzás: 0\nOsztás: 0\n\nÁtlagosan: 100%");
        statTextArea.setEnabled(false);
        jScrollPane1.setViewportView(statTextArea);

        javax.swing.GroupLayout pnStatLayout = new javax.swing.GroupLayout(pnStat);
        pnStat.setLayout(pnStatLayout);
        pnStatLayout.setHorizontalGroup(
            pnStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );
        pnStatLayout.setVerticalGroup(
            pnStatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
        );

        meMuvelet.setText("Müveletek");

        meOsszeadas.setText("Összeadás");
        meMuvelet.add(meOsszeadas);

        meKivonas.setText("Kivonás");
        meMuvelet.add(meKivonas);

        meSzorzas.setText("Szorzás");
        meMuvelet.add(meSzorzas);

        meOsztas.setText("Osztás");
        meOsztas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meOsztasActionPerformed(evt);
            }
        });
        meMuvelet.add(meOsztas);

        meBar.add(meMuvelet);

        setJMenuBar(meBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pnTerulet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnStat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(rbHejes)
                        .addGap(77, 77, 77)
                        .addComponent(rbRossz)
                        .addGap(61, 61, 61)
                        .addComponent(lbUzenet, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnTerulet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnStat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbUzenet, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbHejes)
                            .addComponent(rbRossz))))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int szamgeneral() {
        return (int) (Math.random() * 100);
    }

    private void UjOsztasFeladat() {
        boolean jo = false;
        int oszto, hanyados;
        do {
            oszto = szamgeneral();
            hanyados = szamgeneral();
            jo = oszto > 0 && hanyados > oszto;
        } while (!jo);
        helyesEredmeny = (int) hanyados / oszto;
        lbFeladat.setText(hanyados + "/" + oszto + "=");
    }

    private void UjOszeadas() {
        int szam1 = szamgeneral();
        int szam2 = szamgeneral();
        helyesEredmeny = szam1 + szam2;
        lbFeladat.setText(szam1 + "+" + szam2 + "=");
    }

    private void UjKivonas() {
        int szam1 = szamgeneral();
        int szam2 = szamgeneral();
        helyesEredmeny = szam1 + szam2;
        lbFeladat.setText(szam1 + "+" + szam2 + "=");
    }

    private void UjSzorzas() {
        int szam1 = szamgeneral();
        int szam2 = szamgeneral();
        helyesEredmeny = szam1 * szam2;
        lbFeladat.setText(szam1 + "*" + szam2 + "=");
    }

    private void Proba() {
        probadb++;
        lbProbalkozas.setText("Eddig próbálkozott: " + probadb);
    }

    private void meOsztasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meOsztasActionPerformed
        UjOsztasFeladat();
    }//GEN-LAST:event_meOsztasActionPerformed

    private void btSzamolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSzamolActionPerformed
        if (!lbFeladat.getText().equals("A feladat")) {
            double tipp = 0;
            if (txtTip.getText().length() > 0) {
                tipp = Double.parseDouble(txtTip.getText());
            }
            if ((int) tipp == helyesEredmeny) {
                rbHejes.setSelected(true);

            } else {
                rbRossz.setSelected(true);
                Proba();
            }
        } else {
            lbUzenet.setText("Nincs feladat");
        }
    }//GEN-LAST:event_btSzamolActionPerformed

    private void btUjFeladatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUjFeladatActionPerformed
        HelyesseBT.clearSelection();
        txtTip.setText("");
        lbUzenet.setText("");
        if (lbFeladat.getText().contains("/")) {
            UjOsztasFeladat();
        }
    }//GEN-LAST:event_btUjFeladatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup HelyesseBT;
    private javax.swing.JButton btSzamol;
    private javax.swing.JButton btUjFeladat;
    private javax.swing.JLabel dbKerdes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbFeladat;
    private javax.swing.JLabel lbProbalkozas;
    private javax.swing.JLabel lbUzenet;
    private javax.swing.JMenuBar meBar;
    private javax.swing.JMenuItem meKivonas;
    private javax.swing.JMenu meMuvelet;
    private javax.swing.JMenuItem meOsszeadas;
    private javax.swing.JMenuItem meOsztas;
    private javax.swing.JMenuItem meSzorzas;
    private javax.swing.JPanel pnStat;
    private javax.swing.JPanel pnTerulet;
    private javax.swing.JRadioButton rbHejes;
    private javax.swing.JRadioButton rbRossz;
    private javax.swing.JTextArea statTextArea;
    private javax.swing.JTextField txtTip;
    // End of variables declaration//GEN-END:variables

}
